Core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("", include("todo.urls")),
]

accounts/urls.py
from django.urls import path
from .views import CustomLoginView, RegisterPage

from django.contrib.auth.views import LogoutView

app_name = "accounts"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("logout", LogoutView.as_view(next_page="/"), name="logout"),
    path("register/", RegisterPage.as_view(), name="register"),
]

todo/urls.py
from django.urls import path
from .views import (
    TaskList,
    TaskCreate,
    TaskComplete,
    TaskUpdate,
    DeleteView,
)


urlpatterns = [
    path("", TaskList.as_view(), name="task_list"),
    path("create/", TaskCreate.as_view(), name="create_task"),
    path("update/<int:pk>/", TaskUpdate.as_view(), name="update_task"),
    path("complete/<int:pk>/", TaskComplete.as_view(), name="complete_task"),
    path("delete/<int:pk>/", DeleteView.as_view(), name="delete_task"),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Task(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, null=True, blank=True
    )
    title = models.CharField(max_length=200)
    complete = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        order_with_respect_to = "user"

todo/forms.py
from django import forms
from .models import Task

# Reordering Form and View


class TaskUpdateForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "class": "form-control rounded-4",
                "name": "title",
                "placeholder": "enter the title",
            }
        ),
        label="",
    )

    class Meta:
        model = Task
        fields = ("title",)

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.views import LoginView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.contrib.auth import login
from django.shortcuts import redirect

# Create your views here.


class CustomLoginView(LoginView):
    template_name = "accounts/login.html"
    fields = "username","password"
    redirect_authenticated_user = True

    def get_success_url(self):
        return reverse_lazy("task_list")


class RegisterPage(FormView):
    template_name = "accounts/register.html"
    form_class = UserCreationForm
    redirect_authenticated_user = True
    success_url = reverse_lazy("task_list")

    def form_valid(self, form):
        user = form.save()
        if user is not None:
            login(self.request, user)
        return super(RegisterPage, self).form_valid(form)

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            return redirect("task_list")
        return super(RegisterPage, self).get(*args, **kwargs)

todo/views.py
from django.shortcuts import redirect
from django.views.generic.list import ListView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy

from .forms import TaskUpdateForm
from django.contrib.auth.mixins import LoginRequiredMixin


from django.views import View

from .models import Task


class TaskList(LoginRequiredMixin, ListView):
    model = Task
    context_object_name = "tasks"
    template_name = "todo/list_task.html"

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ["title"]
    success_url = reverse_lazy("task_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(TaskCreate, self).form_valid(form)


class TaskUpdate(LoginRequiredMixin, UpdateView):
    model = Task
    success_url = reverse_lazy("task_list")
    form_class = TaskUpdateForm
    template_name = "todo/update_task.html"
    


class TaskComplete(LoginRequiredMixin, View):
    model = Task
    success_url = reverse_lazy("task_list")

    def get(self, request, *args, **kwargs):
        object = Task.objects.get(id=kwargs.get("pk"))
        object.complete = True
        object.save()
        return redirect(self.success_url)


class DeleteView(LoginRequiredMixin, DeleteView):
    model = Task
    context_object_name = "task"
    success_url = reverse_lazy("task_list")
    template_name = "todo/todo_confirm_delete.html"

    def get(self, request, *args, **kwargs):
        return self.post(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block title %} Login {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:login' %}" method="POST">
        <a href="https://github.com/alibigdeli"><img class="mb-4 rounded-circle border-3 border-white shadow p-1 mb" src="https://icc-aria.ir/static/img/team_11.jpg" alt="" width="150"
            height="150"></a>
        <h1 class="h3 mb-3 fw-normal">Please Sign In</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="username" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>

        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="w-100 btn btn-lg btn-primary" type="submit">Sign In</button>
        <p class="mt-3 mb-2">Dont have an account then <a href="{% url 'accounts:register' %}">create one</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% block title %} Register {% endblock %}

{% block extra_css %}
<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }
</style>
<link href="https://getbootstrap.com/docs/5.1/examples/sign-in/signin.css" rel="stylesheet">
{% endblock %}


{% block content %}
<main class="form-signin text-center">
    <form action="{% url 'accounts:register' %}" method="POST">
        <a href="https://github.com/alibigdeli"><img class="mb-4 rounded-circle border-3 border-white shadow p-1 mb" src="https://icc-aria.ir/static/img/team_11.jpg" alt="" width="150"
            height="150"></a>
        <h1 class="h3 mb-3 fw-normal">Please Register</h1>
        {% csrf_token %}
        <div class="form-floating">
            <input type="username" name="username" class="form-control" id="floatingInput"
                placeholder="name@example.com">
            <label for="floatingInput">Username</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password1" class="form-control mb-0" id="floatingPassword"
                placeholder="Password">
            <label for="floatingPassword">Password</label>
        </div>
        <div class="form-floating">
            <input type="password" name="password2" class="form-control" id="floatingPassword" placeholder="Password">
            <label for="floatingPassword">Repeate Password</label>
        </div>


        <button class="w-100 btn btn-lg btn-primary" type="submit">Register</button>
        <p class="mt-3 mb-2">Already have an account then <a href="{% url 'accounts:login' %}"> login</a></p>
        <p class="mt-5 mb-3 text-muted">&copy; 2017–2021</p>
    </form>
    {% if form.errors %}
    <div class="alert alert-error">
        <h6>Please fix the following errors</h6>
        <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li><a href="#id_{{ field.name }}" class="error">{{ error|escape }}</a></li>
            {% endfor %}
            {% endif %}
            {% endfor %}
        </ul>
        {% if form.non_field_errors %}
        {{ form.non_field_errors }}
        {% endif %}
    </div>
    {% endif %}
</main>


{% endblock %}

todo/templates/base.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Ali Bigdeli">
    <meta name="generator" content="Hugo 0.88.1">
    <title>{% block title %} {% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <style>
        body {
            width: 100%;
            height: 100vh;            
            background: linear-gradient(to bottom, #e6e6e6 0%, #ffffff 100%);
        }
    </style>
    {% block extra_css %}{% endblock %}
</head>

<body>
    {% block content %}{% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ"
        crossorigin="anonymous"></script>
    {% block extra_js %}{% endblock %}
</body>

</html>

todo/templates/todo/list_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Todo List {% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-5 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <!-- <h5 class="modal-title">Modal title</h5> -->
        <h2 class="fw-bold mb-0">Todo App</h2>
        <a type="button" class="btn-close" href="{% url 'accounts:logout' %}"></a>
      </div>

      <div class="modal-body p-5 pt-0">

        <form class="pt-3" method="POST" action="{% url 'create_task' %}">
          {% csrf_token %}
          <div class="input-group mb-3">
            <input type="text" class="form-control rounded-4" name="title" placeholder="Enter task title"
              aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-primary" type="submit">Add</button>
          </div>


          <hr class="my-4">
          {% for task in tasks %}
          <div class="input-group py-1">
            <span type="text" class="form-control" aria-label="Text input with segmented dropdown button">
              {% if task.complete == True %}
              <strike>{{task.title}}</strike>
              {% else %}
              <span>{{task}}</span>
              {% endif %}
            </span>
            <a type="button" class="btn btn-danger" href="{% url 'delete_task' task.id %}"><i class="bi bi-trash"></i></a>
            <button type="button" class="btn btn-primary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown"
              aria-expanded="false">
              <span class="visually-hidden">Toggle Dropdown</span>
            </button>
            <ul class="dropdown-menu dropdown-menu-end">
              <li><a class="dropdown-item" href="{% url 'complete_task' task.id %}">Done</a></li>
              <li><a class="dropdown-item" href="{% url 'update_task' task.id %}">Edit</a></li>
            </ul>
          </div>
      
          {% endfor %}          
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

todo/templates/todo/todo_confirm_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Todo List{% endblock %}
{% block extra_css %}{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2 class="mt-3 mb-3">Are you sure you want to delete "{{ object }}"?</h2>
        
        <form method="post">
            {% csrf_token %}
            <button class="btn btn-primary" type="submit">Yes, delete</button>
            <a class="btn btn-danger ml-2" href="{% url 'task_list' %}">Cancel</a>
        </form>
    </div>
{% endblock %}

{% block extra_js %}{% endblock %}

todo/templates/todo/update_task.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Edit Task {% endblock %}
{% block extra_css %}
{% endblock %}

{% block content %}
<div class="modal modal-signin position-static d-block  py-5" tabindex="-1" role="dialog" id="modalSignin">
	<div class="modal-dialog" role="document">
		<div class="modal-content rounded-5 shadow">
			<div class="modal-header p-5 pb-4 border-bottom-0">
				<!-- <h5 class="modal-title">Modal title</h5> -->
				<h2 class="fw-bold mb-0">Edit Form</h2>
				<a type="button" class="btn-close" href="{% url 'task_list' %}"></a>
			</div>

			<div class="modal-body p-5 pt-0">

				<form method="POST" action="">
					{% csrf_token %}
					<div class="form-floating mb-3">						
                        {{form}}
						<label for="floatingInput">Title</label>
					</div>
					<button class="w-100 mb-2 btn btn-lg rounded-4 btn-primary" type="submit">Change</button>
				</form>				
			</div>
		</div>
	</div>
</div>
{% endblock %}

{% block extra_js %}{% endblock %}

<div class="header-bar">
    <a href="{% url 'tasks' %}">&#8592; Back</a>
</div>


<div class="card-body">
    <form method="POST" action="">
        {% csrf_token %}
        {{form.as_p}}
        <input class="button" type="submit" value="Submit">
    </form>
</div>